apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs
  namespace: argocd            # Argo CD manages it
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vpittamp/nextjs-k8s.git
    targetRevision: HEAD
    path: apps/nextjs/base
  destination:
    name: in-cluster            # same cluster
    namespace: nextjs           # creates its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
