apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: nextjs
data:
  REDIS_URL: "redis://redis-service.redis.svc.cluster.local:6379"
  REDIS_AVAILABLE: "True"

  # public values are OK here
  NEXTAUTH_URL:       "http://chat.localtest.me:31080"
  NEXT_PUBLIC_BASE_URL: "http://chat.localtest.me:31080"
  NEXT_PUBLIC_SITE_URL: "http://chat.localtest.me:31080"