apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: nextjs
data:
  REDIS_URL: "redis://redis-service.redis.svc.cluster.local:6379"
  REDIS_AVAILABLE: "True"
  POSTGRES_URL: "postgresql://postgres:postgres@postgres-service.nextjs.svc.cluster.local:5432/postgres"

  # public values are OK here
  NEXTAUTH_URL:       "http://localhost:30000"
  NEXT_PUBLIC_BASE_URL: "http://localhost:30000"
  TRUST_PROXY: "1"
