apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: nextjs 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: vpittamp-acr-dockercfg   # secret produced by ESO
      containers:
      - name: nextjs
        image: vpittamp.azurecr.io/chat-frontend:0.2.0
        envFrom:
        - secretRef:   { name: app-env }      # <── renamed-secret values
        - configMapRef:{ name: myapp-config } # <── public values
        env:                                   # keys that need a *specific* source
        - name: POSTGRES_URL                   # Drizzle expects this exact var :contentReference[oaicite:2]{index=2}
          valueFrom: { secretKeyRef: { name: app-env, key: POSTGRES_URL } }
        livenessProbe:
          httpGet: { path: /ping, port: 3000 }
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: { path: /ping, port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10