apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: nextjs 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: vpittamp-acr-dockercfg   # secret produced by ESO
      containers:
      - name: nextjs
        image: vpittamp.azurecr.io/chat-frontend:0.2.0
        envFrom:
        - secretRef:
            name: kv-vault 
        - configMapRef: { name: myapp-config }
          
        env:
          - name: NEXTAUTH_URL
            valueFrom: { configMapKeyRef: { name: myapp-config, key: NEXTAUTH_URL } }
          - name: NEXT_PUBLIC_SITE_URL
            valueFrom: { configMapKeyRef: { name: myapp-config, key: NEXT_PUBLIC_SITE_URL } }
          - name: TRUST_PROXY
            value: "1"
          - name: POSTGRES_URL
            valueFrom: { configMapKeyRef: { name: myapp-config, key: POSTGRES_URL } }
