apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: nextjs 
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
