# apps/infra-secrets/base/externalsecrets-app-env.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-env            # <── new Secret will be called app-env
  namespace: nextjs
spec:
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: app-env          # ← the Secret the pod will mount
    creationPolicy: Owner
  data:                    # one-by-one mapping (hyphen → underscore)
    - secretKey: OPENAI_API_KEY
      remoteRef: { key: OPENAI-API-KEY }
    - secretKey: AZURE_API_KEY
      remoteRef: { key: AZURE-API-KEY }
    - secretKey: ANTHROPIC_API_KEY
      remoteRef: { key: ANTHROPIC-API-KEY }
    - secretKey: XAI_API_KEY
      remoteRef: { key: XAI-API-KEY }
    - secretKey: NEXTAUTH_SECRET
      remoteRef: { key: NEXTAUTH-SECRET }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: POSTGRES-PASSWORD }
    - secretKey: POSTGRES_URL          # ← this replaces DEV-POSTGRES-URL
      remoteRef: { key: POSTGRES-URL }
