apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-sa
  namespace: nextjs
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: bcfe91bf-db7b-43ee-9ea3-235a8c3058d0
    azure.workload.identity/tenant-id: 0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38