apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-sa
  namespace: nextjs
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 66506bf3-428e-451f-a642-0c3896c5448e
    azure.workload.identity/tenant-id: 0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38