# apps/postgres/base/pv.yaml  (rename file or adjust metadata.name)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-local-pv-v2            # NEW name
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  storageClassName: ""            # static
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres          # identical path
    type: DirectoryOrCreate
