# apps/postgres/base/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: nextjs
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ""            # must match the PV above
  resources:
    requests:
      storage: 5Gi
