# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nextjs
spec:
  selector: { app: postgres }
  ports:
    - { name: pg, port: 5432, targetPort: 5432 }
  type: ClusterIP
